### ISSUE TITLE
The total length of the temporal STGAN dataset is 3130, not 3101 as described in your paper

### ISSUE THREAD

**Issue by XavierJiezou** [come880412/CTGAN#1]
Hello,

I have downloaded the STGAN dataset. After unzipping, I found 3132 images in the clear folder including two error images that cannot be opened. But according to the description in section 3.1 of your paper, the total number of images is 3101, which does not match the number 3130. 

I have read the STGAN paper and encountered the same problem. Can you tell me how you solved the problem? Or is there something I haven't noticed?

Thank you.

**Comment by come880412** [comment]
Hello,

I just followed the description of STGAN paper to write it.
I forgot the actual number of images in their dataset. I think maybe there are some duplicate images in this dataset.
If you would like to know more details, I suggest you can send an email to STGAN's authors to ask.

Hope this helps!

Thank you.

**Comment by XavierJiezou** [comment]
I have checked all the images, but no duplicate can be found. I have emailed STGAN's authors for more details, thanks again.
