### ISSUE TITLE
I have downloaded your dataset named Sen2 MTC, but there are only 49 non-overlapping tiles

### ISSUE THREAD

**Issue by XavierJiezou** [come880412/CTGAN#2]
Hi,

I downloaded your dataset named `Sen2 MTC`, but there are only 49 non-overlapping tiles, which is inconsistent with the length of 50 reported in your paper. In addition, not every tile has 70 images, there are 56 images in the tile named `T31TBG_R051` and 71 images in the tile named `T41UNR_R020`. So I guess what is reported in the paper is an approximate number, can I understand it this way?

Thanks.

**Comment by come880412** [comment]
Yes, you are right.
The reported images and the length of the tiles are approximate numbers.
But if you would like to compare the performance reported in the paper, you can still use the same split situation.

Hope this helps.

Thanks.

**Comment by XavierJiezou** [comment]
I got it. Thank you for your work and patient response!

**Comment by XavierJiezou** [comment]
I got it! Thank you for the work and patient reply.

**Comment by come880412** [comment]
You're welcome. I'm glad this work was helpful.
